services:
  localdb:
    container_name: hanaro-mysql
    image: mysql:8.0
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: TestdbRoot
      MYSQL_DATABASE: hanadb
      MYSQL_USER: hanaro
      MYSQL_PASSWORD: 12345678
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
      - --default-time-zone=Asia/Seoul
      - --innodb_ft_min_token_size=2
      - --innodb_ft_server_stopword_table=hanadb/StopWord

    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
